version: '1.0'

services:
  go-app:
    container_name: go-app
    image: francescoxx/go-app:1.0.0
    build: .
    environment:
      MONGO_URI: "mongodb://mongo_db:27017/go_db"
    ports:
      - "8000:8000"
    depends_on:
      - mongo_db
  mongo_db:
    container_name: mongo_db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:  
  mongodata: {}

